### ISSUE TITLE
List templates?

### ISSUE THREAD

**Issue by parkr** [robfig/soy#22]
Hey!

Cool library, thanks for writing it. :facepunch: 

How can I list the templates once I have `soyhtml.Tofu`? I'd like to output a list of all available templates in a help page.

**Comment by robfig** [comment]
Hey, thanks! 

Yeah, for all more advanced stuff you have to use soy.Bundle.Compile() instead of CompileToTofu().  That gives you a template.Registry that you can work with.  (Maybe I should make that accessible from the tofu too... )

For example
```
reg, _ := soy.NewBundle()
  .. add files/directories .. 
  .Compile()
for _, t := range reg.Templates {
  fmt.Println(t.Name)
}
tofu := soyhtml.NewTofu(reg)
```

Definitely let me know if you have any feedback on the library / API ! 

Enjoy,
Rob
