### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jimbojetlag** [robfig/soy#57]
The TODO file has not been updated for over 4 years. Is this project still active?

Is this package safe to be used in production?

**Comment by robfig** [comment]
It is used to generate hundreds of brand name sites representing > 1B page views per year, so I think it's safe. It is not under active development because it has been doing its job just fine. 

Note that I have not had the time to add the new features introduced in (and since) the April 2014 release of the Java project, notably strict auto-escaping. Contributions welcome

**Comment by jimbojetlag** [comment]
Great to know that it's heavily used in production! Would it be possible to have links to some of these production examples?

**Comment by robfig** [comment]
Here's a testimonial from Arby's
https://www.yext.com/customers/arbys/

Pages served here
https://locations.arbys.com/ny.html
